### ISSUE TITLE
Fllow the cookbook I get a problem not fund the authorizationservice 

### ISSUE THREAD

**Issue by Dreamseekai** [ZF-Commons/zfc-rbac#370]
class Module
{
    // getAutoloaderConfig(), getConfig(), etc...

    public function getServiceConfig()
    {
        return [
            'factories' => [
                 'PostService' => function($sm) {
                     return new PostService(
                         $sm->get('doctrine.entitymanager.orm_default'),
                         $sm->get('ZfcRbac\Service\AuthorizationService') // This is new!
                     );
                 }
            ]
        ];   Can not fund the ZfcRbac\Service\AuthorizationService?why. And how fix it?

**Comment by basz** [comment]
Are you sure you have registered the ZfcRbac Module in config/application.php Looks like this https://github.com/ZF-Commons/zfc-rbac/blob/master/config/module.config.php#L33 configuration isn’t active…

**Comment by Dreamseekai** [comment]
first thank you for your answer.
sorry i make i mistake.... the issues is worng ... 
second
look here please-----
 Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "Zend\Authentication\AuthenticationService" to a factory; are you certain you provided it during configuration? in D:\phpStudy\WWW\ZF3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php:681 Stack trace: #0 D:\phpStudy\WWW\ZF3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(757): Zend\ServiceManager\ServiceManager->getFactory('Zend\\Authentica...') #1 D:\phpStudy\WWW\ZF3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Zend\\Authentica...') #2 D:\phpStudy\WWW\ZF3\vendor\zf-commons\zfc-rbac\src\ZfcRbac\Factory\AuthenticationIdentityProviderFactory.php(43): Zend\ServiceManager\ServiceManager->get('Zend\\Authentica...') #3 D:\phpStudy\WWW\ZF3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(758): ZfcRbac\Factory\AuthenticationIdentityProviderFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'ZfcRbac\\Id in D:\phpStudy\WWW\ZF3\vendor\zendframework\zend-servicemanager\src\ServiceManager.php on line 681


i flow  the cookbook get this fatal error~~ please give me sime idea~

**Comment by ashatrov** [comment]
@basz Hi! I have same issue with PHP7.0.18 + ZF2.5.3 + ZF-Commons/zfc-rbac 2.6.2

The issue in \ZfcRbac\Factory\RoleServiceFactory

with this code:
`$roleProvider = $pluginManager->get(key($roleProviderConfig), current($roleProviderConfig));`

The internal pointer in array $roleProviderConfig is in the end of array, because of that `key($roleProviderConfig)` and `current($roleProviderConfig)` return null.

There is two options to fix it on place:
1. Reset internal pointer in array to the beginning:
```
reset($roleProviderConfig);
$roleProvider = $pluginManager->get(key($roleProviderConfig), current($roleProviderConfig));
```
2. Use different functions, which work without pointer.
```
$roleProvider = $pluginManager->get(array_keys($roleProviderConfig)[0], $roleProviderConfig[array_keys($roleProviderConfig)[0]]);
```

I think first is better and it is good practice to get first element of associative array.

**Comment by prolic** [comment]
@ashatrov can you provide a PR including tests?
